version: '3.8'

services:
  asterisk:
    image: andrius/asterisk
    container_name: asterisk
    restart: unless-stopped
    ports:
      - "2500:5060/udp"
      - "2500:5060/tcp"
      - "8088:8088/tcp"
      - "10000-10100:10000-10100/udp"
    volumes:
      - ./config/ari.conf:/etc/asterisk/ari.conf
      - ./config/extensions.conf:/etc/asterisk/extensions.conf
      - ./config/http.conf:/etc/asterisk/http.conf
      - ./config/pjsip.conf:/etc/asterisk/pjsip.conf
      - ./config/hello.wav:/var/lib/asterisk/sounds/en/hello-world.wav