version: '3.8'

services:
  asterisk:
    image: andrius/asterisk
    container_name: asterisk
    restart: unless-stopped
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "8088:8088/tcp"
      - "10000-10100:10000-10100/udp"
    volumes:
      - ./config/ari.conf:/etc/asterisk/ari.conf
      - ./config/extensions.conf:/etc/asterisk/extensions.conf
      - ./config/http.conf:/etc/asterisk/http.conf
      - ./config/pjsip.conf:/etc/asterisk/pjsip.conf
      - ./config/rtp.conf:/etc/asterisk/rtp.conf
      - ./ari_server/sounds:/var/lib/asterisk/sounds
    networks:
      - ia-network

  ari-server:
    build: ./ari_server
    container_name: ari-server
    restart: unless-stopped
    depends_on:
      - asterisk
    networks:
      - ia-network

networks:
  ia-network:
    driver: bridge